"""UserTower: encodes user profile + behavior features into 64-dim embedding."""

from __future__ import annotations

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout, Embedding, LayerNormalization

from src.data.schema import (
    EMB_CONFIG,
    EmbeddingConfig,
    NUM_HOME_COUNTRIES,
    NUM_ITEM_CATEGORIES,
    NUM_TRAVEL_STYLES,
    NUM_TRAVEL_THEMES,
)


class UserTower(keras.Model):
    """Encodes user features into the shared 64-dim embedding space.

    Profile features (age, country, style, theme, context) come from
    preprocessed user_profiles. Behavior features (category_pref_indices,
    category_interaction_history, subcat_affinity) are generated by
    behavior_generator.py and must be present at training/inference time.

    All variable-length index inputs are padded with -1. Valid indices >= 0.

    Architecture:
        feature embeddings + dense projections
        → concat → LayerNorm → Dense(256, relu) → Dense(128, relu) → Dense(64)
        → L2-normalize
    """

    def __init__(
        self,
        config: EmbeddingConfig = EMB_CONFIG,
        dropout_rate: float = 0.1,
    ) -> None:
        super().__init__()
        self.config = config

        # Embedding layers for categorical features
        self.home_country_emb = Embedding(NUM_HOME_COUNTRIES, config.home_country_emb_dim)
        self.travel_style_emb = Embedding(NUM_TRAVEL_STYLES, config.travel_style_emb_dim)
        self.travel_theme_emb = Embedding(NUM_TRAVEL_THEMES, config.travel_theme_emb_dim)
        # category_pref_indices span the unified 69-dim item-category vocab
        self.category_pref_emb = Embedding(NUM_ITEM_CATEGORIES, config.attraction_subcat_emb_dim)

        # Dense projections for dense float behavior vectors
        self.cat_hist_proj = Dense(32, activation="relu")   # (69,) → (32,)
        self.subcat_aff_proj = Dense(32, activation="relu")  # (58,) → (32,)

        # Tower MLP head
        self.layer_norm = LayerNormalization()
        self.dense1 = Dense(256, activation="relu")
        self.dense2 = Dense(128, activation="relu")
        self.output_proj = Dense(config.output_dim)
        self.dropout = Dropout(dropout_rate)

    @staticmethod
    def _masked_mean_pool(indices: tf.Tensor, emb_layer: Embedding) -> tf.Tensor:
        """Embedding lookup + mean pool over valid (non-padding) positions.

        Args:
            indices: int32 [B, L], -1 = padding sentinel.
            emb_layer: Keras Embedding layer.

        Returns:
            float32 [B, D] mean-pooled embedding, zero vector when all padding.
        """
        mask = tf.cast(indices >= 0, tf.float32)           # [B, L]
        safe = tf.maximum(indices, 0)                       # clip -1 → 0 for safe lookup
        emb = emb_layer(safe)                               # [B, L, D]
        emb = emb * mask[:, :, tf.newaxis]                  # zero out padding positions
        count = tf.reduce_sum(mask, axis=1, keepdims=True)  # [B, 1]
        return tf.reduce_sum(emb, axis=1) / tf.maximum(count, 1.0)

    def call(self, inputs: dict, training: bool = False) -> tf.Tensor:
        """Encode user features into the shared embedding space.

        Args:
            inputs: dict with keys matching UserFeatureSchema field names.
            training: passed to Dropout layers.

        Returns:
            float32 [B, output_dim] L2-normalized user embedding.
        """
        # Scalar profile features
        age = tf.expand_dims(tf.cast(inputs["age_norm"], tf.float32), -1)  # [B, 1]
        country = self.home_country_emb(inputs["home_country_id"])          # [B, D_c]

        # Pooled multi-hot embedding features
        style = self._masked_mean_pool(inputs["travel_style_indices"], self.travel_style_emb)
        theme = self._masked_mean_pool(inputs["travel_theme_indices"], self.travel_theme_emb)
        cat_pref = self._masked_mean_pool(inputs["category_pref_indices"], self.category_pref_emb)

        # Dense behavior features
        cat_hist = self.cat_hist_proj(
            tf.cast(inputs["category_interaction_history"], tf.float32)
        )
        subcat_aff = self.subcat_aff_proj(
            tf.cast(inputs["subcat_affinity"], tf.float32)
        )

        # Cyclical context features
        day_sin = tf.expand_dims(tf.cast(inputs["context_day_sin"], tf.float32), -1)
        day_cos = tf.expand_dims(tf.cast(inputs["context_day_cos"], tf.float32), -1)
        hour_sin = tf.expand_dims(tf.cast(inputs["context_hour_sin"], tf.float32), -1)
        hour_cos = tf.expand_dims(tf.cast(inputs["context_hour_cos"], tf.float32), -1)

        # Concatenate all feature parts
        x = tf.concat(
            [
                age, country, style, theme, cat_pref,
                cat_hist, subcat_aff,
                day_sin, day_cos, hour_sin, hour_cos,
            ],
            axis=-1,
        )

        # MLP head
        x = self.layer_norm(x)
        x = self.dropout(self.dense1(x), training=training)
        x = self.dropout(self.dense2(x), training=training)
        x = self.output_proj(x)
        return tf.nn.l2_normalize(x, axis=-1)
